# environment
env_prefix: ce_
ingress_dns_name: ota.local
kafka_host: kafka
kafka_topic_suffix: ce
mysql_host: mysql
image_pull_secrets_name: docker-registry-key
zookeeper_host: zookeeper

# images
app_docker_image: advancedtelematic/ota-plus-web:0.6.0-19-g4adbd77
campaigner_docker_image: advancedtelematic/campaigner:0.0.1-67-g27d5d9b
device_registry_docker_image: advancedtelematic/device-registry:0.0.1-14-g0a1af2e
director_daemon_docker_image: advancedtelematic/director:0.2.0-6-g916d772
director_docker_image: advancedtelematic/director:0.2.0-6-g916d772
kafka_docker_image: confluentinc/cp-kafka:4.0.0
mysql_docker_image: mariadb:10.3.2
sota_core_docker_image: advancedtelematic/sota-core:0.3.25
treehub_docker_image: advancedtelematic/treehub:0.1.12
tuf_keyserver_daemon_docker_image: advancedtelematic/tuf-keyserver:0.2.0-54-g1e7a646
tuf_keyserver_docker_image: advancedtelematic/tuf-keyserver:0.2.0-54-g1e7a646
tuf_reposerver_docker_image: advancedtelematic/tuf-reposerver:0.2.0-54-g1e7a646
tuf_vault_docker_image: advancedtelematic/crypto-vault:0.3
web_events_docker_image: advancedtelematic/web-events:0.0.7
zookeeper_docker_image: gcr.io/google_samples/k8szk:v2

# services
app_cpu: 80m
app_java_opts: "-Xmx300m"
app_jwt_secret: youshouldreplacethiswithsomeotherlongsecret
app_mem: 350Mi
app_play_crypto_secret: youshouldreplacethiswithsomeotherlongsecret
campaigner_cpu: 80m
campaigner_daemon_cpu: 80m
campaigner_daemon_db_password: campaigner
campaigner_daemon_db_user: campaigner
campaigner_daemon_java_opts: "-Xmx200m"
campaigner_daemon_mem: 250Mi
campaigner_db_password: campaigner
campaigner_db_user: campaigner
campaigner_java_opts: "-Xmx200m"
campaigner_mem: 250Mi
device_registry_cpu: 80m
device_registry_db_password: device_registry
device_registry_db_user: device_registry
device_registry_java_opts: "-Xmx250m"
device_registry_mem: 300Mi
director_cpu: 80m
director_daemon_cpu: 80m
director_daemon_db_password: director
director_daemon_db_user: director
director_daemon_java_opts: "-Xmx250m"
director_daemon_mem: 200Mi
director_db_password: director
director_db_user: director
director_java_opts: "-Xmx150m"
director_mem: 200Mi
kafka_cpu: 80m
kafka_mem: 400Mi
mysql_root_password: root
sota_core_aws_key: AKIA01234567890ABCD
sota_core_aws_secret: abcdefghijklmnopqrstuvwxyz1234567890ABCD
sota_core_cpu: 80m
sota_core_db_password: sota_core
sota_core_db_user: sota_core
sota_core_java_opts: "-Xmx150m"
sota_core_jwt_secret: youshouldreplacethiswithsomeotherlongsecret
sota_core_mem: 250Mi
treehub_aws_key: AKIA01234567890ABCD
treehub_aws_secret: abcdefghijklmnopqrstuvwxyz1234567890ABCD
treehub_cpu: 80m
treehub_db_password: treehub
treehub_db_user: treehub
treehub_java_opts: "-Xmx80m"
treehub_jwt_secret: youshouldreplacethiswithsomeotherlongsecret
treehub_mem: 100Mi
tuf_keyserver_daemon_cpu: 80m
tuf_keyserver_daemon_db_password: tuf_keyserver
tuf_keyserver_daemon_db_user: tuf_keyserver
tuf_keyserver_daemon_java_opts: "-Xmx250m"
tuf_keyserver_daemon_mem: 300Mi
tuf_keyserver_daemon_vault_token: 123e4567-e89b-12d3-a456-426655440000
tuf_keyserver_cpu: 80m
tuf_keyserver_db_password: tuf_keyserver
tuf_keyserver_db_user: tuf_keyserver
tuf_keyserver_java_opts: "-Xmx250m"
tuf_keyserver_mem: 300Mi
tuf_reposerver_aws_key: AKIA01234567890ABCD
tuf_reposerver_aws_secret: abcdefghijklmnopqrstuvwxyz1234567890ABCD
tuf_reposerver_cpu: 80m
tuf_reposerver_db_password: tuf_reposerver
tuf_reposerver_db_user: tuf_reposerver
tuf_reposerver_java_opts: "-Xmx250m"
tuf_reposerver_mem: 300Mi
tuf_reposerver_pub_db_password: tuf_reposerver
tuf_reposerver_pub_db_user: tuf_reposerver
tuf_vault_cpu: 80m
tuf_vault_db_password: tuf_vault
tuf_vault_db_user: tuf_vault
tuf_vault_mem: 40Mi
web_events_cpu: 80m
web_events_jwt_secret: youshouldreplacethiswithsomeotherlongsecret
web_events_mem: 250Mi
zookeeper_cpu: 10m
zookeeper_mem: 100Mi
