# environment
envPrefix: ce_
externalDomain: ota.local
javaOpts: "-Xmx400m"
kafkaHost: kafka
kafkaTopicPrefix: ce
mysqlHost: mysql
zookeeperHost: zookeeper

# images
appImage: advancedtelematic/ota-plus-web:0.5.3-5-g31c7fe9
campaignerImage: advancedtelematic/campaigner:0.0.1-64-g1d25684
deviceRegistryImage: advancedtelematic/sota-device_registry:0.3.23
directorImage: advancedtelematic/director:0.2.0-1-gdae1759
kafkaImage: databench/apache-kafka-basic:0.4.0
mysqlImage: mariadb:10.3.2
sotaCoreImage: advancedtelematic/sota-core:0.3.23
treehubImage: advancedtelematic/treehub:0.1.8
tufKeyserverImage: advancedtelematic/tuf-keyserver:0.2.0-31-ge596ad8
tufReposerverImage: advancedtelematic/tuf-reposerver:0.2.0-31-ge596ad8
tufVaultImage: advancedtelematic/crypto-vault:0.3
tufVaultBootstrapImage: advancedtelematic/bootstrap_ota_kube:1.6
webEventsImage: advancedtelematic/web-events:0.0.7
zookeeperImage: databench/apache-kafka-basic:0.4.0

# resources
appCpu: 80m
appMemory: 500Mi
campaignerCpu: 80m
campaignerMemory: 500Mi
campaignerDaemonCpu: 80m
campaignerDaemonMemory: 500Mi
deviceRegistryCpu: 80m
deviceRegistryMemory: 500Mi
directorCpu: 80m
directorMemory: 500Mi
directorDaemonCpu: 80m
directorDaemonMemory: 500Mi
kafkaCpu: 80m
kafkaMemory: 500Mi
sotaCoreCpu: 80m
sotaCoreMemory: 500Mi
treehubCpu: 80m
treehubMemory: 500Mi
tufKeyserverCpu: 80m
tufKeyserverMemory: 500Mi
tufKeyserverDaemonCpu: 80m
tufKeyserverDaemonMemory: 500Mi
tufReposerverCpu: 80m
tufReposerverMemory: 500Mi
tufVaultCpu: 80m
tufVaultMemory: 500Mi
webEventsCpu: 80m
webEventsMemory: 500Mi
zookeeperCpu: 80m
zookeeperMemory: 500Mi
