---
apiVersion: v1
kind: ConfigMap
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/campaigner
  DB_USER: campaigner
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  DIRECTOR_HOST: director
  DIRECTOR_PORT: '80'
  ENV_PREFIX: ce_
  INFLUXDB_HOST: influx.k8s
  INFLUXDB_PORT: '8086'
  JAVA_OPTS: ''
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  MESSAGING_MODE: kafka
  METRICS_DB: services
  SCHEDULER_BATCH_SIZE: '200'
  SCHEDULER_DELAY: 10 seconds
  SCHEDULER_POLLING_TIMEOUT: 10 seconds
  INFLUXDB_URI: http://influx.k8s:8086
metadata:
  name: campaigner-daemon-config
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: campaigner-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: campaigner-daemon
    spec:
      containers:
      - image: advancedtelematic/campaigner:0.0.1-64-g1d25684
        name: campaigner-daemon
        envFrom:
        - configMapRef:
            name: campaigner-daemon-config
        - secretRef:
            name: campaigner-daemon-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: camp-daem0
        args:
        - "-main"
        - com.advancedtelematic.campaigner.DaemonBoot
        resources:
          requests:
            cpu: '0.2'
            memory: 1024Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: campaigner-daemon
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: campaigner-daemon.external.kube.atsgarage.com
    http:
      paths:
      - backend:
          serviceName: campaigner-daemon
          servicePort: 80
---
apiVersion: v1
kind: Secret
type: Opaque
data:
  DB_PASSWORD: ${CAMPAIGNER_DAEMON_DB_PASSWORD}
metadata:
  name: campaigner-daemon-secret
