---
apiVersion: v1
kind: ConfigMap
metadata:
  name: director-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/director
  DB_USER: director
  ENV_PREFIX: ce_
  JAVA_OPTS: "-Xmx400m"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: director
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: director
    spec:
      containers:
      - image: {{ .directorImage }}
        name: director
        envFrom:
        - configMapRef:
            name: director-config
        - secretRef:
            name: director-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: director0
        args:
        resources:
          requests:
            cpu: '0.1'
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: director
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: director.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: director
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: director-secret
type: Opaque
data:
  DB_PASSWORD: {{ .directorDbPassword | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: director
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: director0
  selector:
    app: director
