# infra images
default_docker_image: docker:18.03
default_http_docker_image: gcr.io/google_containers/defaultbackend:1.4
ingress_controller_docker_image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0
init_docker_image: busybox:1.28.0
kafka_docker_image: confluentinc/cp-kafka:4.0.0
mysql_docker_image: mariadb:10.3.2
nginx_docker_image: nginx:1.13.7
pause_docker_image: gcr.io/google_containers/pause:3.0
zookeeper_docker_image: gcr.io/google_samples/k8szk:v2

# service images
app_docker_image: advancedtelematic/ota-plus-web:0.7.3-16-g30b1c15
bootstrap_docker_image: advancedtelematic/bootstrap_ota_kube:2.1
campaigner_docker_image: advancedtelematic/campaigner:0.0.1-71-gf80181b
campaigner_daemon_docker_image: advancedtelematic/campaigner:0.0.1-71-gf80181b
crypt_vault_docker_image: advancedtelematic/crypto-vault:0.3
device_registry_docker_image: advancedtelematic/device-registry:0.0.1-27-gf10bc67
director_daemon_docker_image: advancedtelematic/director:0.2.0-27-gcd592e6
director_docker_image: advancedtelematic/director:0.2.0-27-gcd592e6
treehub_docker_image: advancedtelematic/treehub:0.1.18
tuf_keyserver_daemon_docker_image: advancedtelematic/tuf-keyserver:0.3.0-16-gfde0883
tuf_keyserver_docker_image: advancedtelematic/tuf-keyserver:0.3.0-16-gfde0883
tuf_reposerver_docker_image: advancedtelematic/tuf-reposerver:0.3.0-16-gfde0883
web_events_docker_image: advancedtelematic/web-events:0.0.13
