# infra images
default_docker_image: docker:18.03
default_http_docker_image: gcr.io/google_containers/defaultbackend:1.4
ingress_controller_docker_image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0
init_docker_image: busybox:1.28.0
kafka_docker_image: confluentinc/cp-kafka:4.0.0
mysql_docker_image: mariadb:10.3.2
nginx_docker_image: nginx:1.13.7
pause_docker_image: gcr.io/google_containers/pause:3.0
zookeeper_docker_image: gcr.io/google_samples/k8szk:v2

# service images
app_docker_image: advancedtelematic/ota-plus-web:f5d02d1a7cc284397e07b1b79104cbeccac78078
bootstrap_docker_image: advancedtelematic/bootstrap_ota_kube:2.1
campaigner_docker_image: advancedtelematic/campaigner:ebc1f5771021ef40fff63f966178da34a5d7ecd9
campaigner_daemon_docker_image: advancedtelematic/campaigner:0.0.1-71-gf80181b
device_registry_docker_image: advancedtelematic/device-registry:5494d76722fd6a31a50645c9fd296030d0021958
director_daemon_docker_image: advancedtelematic/director-v2:eb75c8bd21b36e7809397cecf9fc652d611e49d3
director_docker_image: advancedtelematic/director-v2:eb75c8bd21b36e7809397cecf9fc652d611e49d3
treehub_docker_image: advancedtelematic/treehub:96fa7bfb72cec63947fbc40127bbb86983fdda3b
tuf_keyserver_daemon_docker_image: advancedtelematic/tuf-keyserver:1d0d714a6ff42d2f041fa1bfd0eb2330ccbbf836
tuf_keyserver_docker_image: advancedtelematic/tuf-keyserver:1d0d714a6ff42d2f041fa1bfd0eb2330ccbbf836
tuf_reposerver_docker_image: advancedtelematic/tuf-reposerver:1d0d714a6ff42d2f041fa1bfd0eb2330ccbbf836
web_events_docker_image: advancedtelematic/web-events:caed58ec6c814f4df72d5c1e5c5c68c9856fd3c0
