tuf-reposerver: advancedtelematic/tuf-reposerver:29f592227c60e1994def3f53f84d3dd8beb4b788
web-events: advancedtelematic/web-events:b2eac7851275bd2caf2ec38000193a45a2d1e5de
director: advancedtelematic/director-v2:439ba2ad56a584916174dbb36561cb0d80e918f0
tuf-keyserver: advancedtelematic/tuf-keyserver:67546531299488922eec90d239b61777947aeda4
app: advancedtelematic/ota-plus-web:212edf5938451ead3fd80875de83a41379014a5c
campaigner: advancedtelematic/campaigner:744bab6285806cb52d2ae02ab6d58c80c73e0ff5
device-registry: advancedtelematic/device-registry:16bb1c370c9fb89f292aa5365c778ed1f3aeb51e
treehub: advancedtelematic/treehub:a34c250106feccf7ec04fe398ca82bd7104a7c45
