---
app_cpu: 80m
app_java_opts: '-Xmx300m'
app_mem: 350Mi

campaigner_cpu: 80m
campaigner_daemon_cpu: 80m
campaigner_daemon_java_opts: '-Xmx200m'
campaigner_daemon_mem: 250Mi
campaigner_java_opts: '-Xmx200m'
campaigner_mem: 250Mi

crypt_vault_cpu: 80m
crypt_vault_mem: 40Mi

device_registry_cpu: 80m
device_registry_java_opts: "-Xmx250m"
device_registry_mem: 300Mi

director_cpu: 80m
director_daemon_cpu: 80m
director_daemon_java_opts: "-Xmx200m"
director_daemon_mem: 200Mi
director_java_opts: "-Xmx250m"
director_mem: 300Mi

kafka_cpu: 80m
kafka_disk: 10Gi
kafka_host: kafka
kafka_mem: 400Mi

mysql_disk: 10Gi
mysql_host: mysql

sota_core_cpu: 0.1
sota_core_java_opts: "-Xmx150m"
sota_core_mem: 200Mi

treehub_cpu: 80m
treehub_disk: 10Gi
treehub_java_opts: "-Xmx80m"
treehub_mem: 100Mi
treehub_storage: local

tuf_keyserver_cpu: 80m
tuf_keyserver_daemon_cpu: 80m
tuf_keyserver_daemon_java_opts: "-Xmx250m"
tuf_keyserver_daemon_mem: 300Mi
tuf_keyserver_java_opts: "-Xmx250m"
tuf_keyserver_mem: 300Mi

tuf_reposerver_cpu: 80m
tuf_reposerver_java_opts: "-Xmx250m"
tuf_reposerver_local_storage_root: "/tmp/tuf-targets"
tuf_reposerver_mem: 300Mi

tuf_vault_cpu: 80m
tuf_vault_mem: 40Mi

web_events_cpu: 80m
web_events_mem: 250Mi

zookeeper_cpu: 20m
zookeeper_disk: 10Gi
zookeeper_host: zookeeper
zookeeper_mem: 100Mi

create_ingress: true
