---
app_play_crypto_secret: youshouldreplacethiswithsomeotherlongsecretvalue
campaigner_daemon_db_password: campaigner
campaigner_daemon_db_user: campaigner
campaigner_db_password: campaigner
campaigner_db_user: campaigner
crypt_vault_db_user: crypt_vault
crypt_vault_db_password: crypt_vault
device_registry_db_password: device_registry
device_registry_db_user: device_registry
director_daemon_db_password: director
director_daemon_db_user: director
director_db_password: director
director_db_user: director
mysql_root_password: root
jwt_secret: youshouldreplacethiswithsomeotherlongsecretvalue
sota_core_db_password: sota_core
sota_core_db_user: sota_core
treehub_aws_key: akiaabcdefghijklmnop
treehub_aws_secret: abcdefghijklmnopqrstuvwxyz1234567890abcd
treehub_auth_protocol: none
treehub_db_password: treehub
treehub_db_user: treehub
tuf_keyserver_daemon_db_password: tuf_keyserver
tuf_keyserver_daemon_db_user: tuf_keyserver
tuf_keyserver_db_password: tuf_keyserver
tuf_keyserver_db_user: tuf_keyserver
tuf_reposerver_aws_key: akiaabcdefghijklmnop
tuf_reposerver_aws_secret: abcdefghijklmnopqrstuvwxyz1234567890abcd
tuf_reposerver_db_password: tuf_reposerver
tuf_reposerver_db_user: tuf_reposerver
tuf_vault_db_user: tuf_vault
tuf_vault_db_password: tuf_vault
