---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sota-core-config
data:
  AUTH_PROTOCOL: none
  BIND_HOST: 0.0.0.0
  BIND_PORT: '9001'
  CORE_AWS_BUCKET_ID: ats-k8s-core
  CORE_DB_URL: jdbc:mariadb://mysql:3306/sota_core
  CORE_DB_USER: sota_core
  CORE_INTERACTION_PROTOCOL: none
  DB_MIGRATE: 'true'
  DEVICE_REGISTRY_HOST: device-registry
  DEVICE_REGISTRY_PORT: '80'
  ENV_PREFIX: ce_
  JAVA_OPTS: "-Xmx400m"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  MESSAGING_MODE: kafka
  PACKAGES_VERSION_FORMAT: ".+"
  REPORT_METRICS: "false"
  SOTA_RESOLVER_PORT: '80'
  TUF_REPOSERVER_HOST: tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  USE_TUF: 'true'
  USE_USER_PROFILE: 'false'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sota-core
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sota-core
    spec:
      containers:
      - image: {{ .sotaCoreImage }}
        name: sota-core
        envFrom:
        - configMapRef:
            name: sota-core-config
        - secretRef:
            name: sota-core-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: sota-core0
        args:
        resources:
          requests:
            cpu: '0.1'
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sota-core
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sota-core.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: sota-core
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: sota-core-secret
type: Opaque
data:
  CORE_DB_PASSWORD: {{ .sotaCoreDbPassword | b64enc }}
  JWT_SECRET: {{ .sotaCoreJwtSecret | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: sota-core
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: sota-core0
  selector:
    app: sota-core
