---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-keyserver-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/tuf_keyserver
  DB_USER: tuf_keyserver
  JAVA_OPTS: "-Xmx400m"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  REPORT_METRICS: "false"
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-keyserver
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver
    spec:
      containers:
      - image: {{ .tufKeyserverImage }}
        name: tuf-keyserver
        envFrom:
        - configMapRef:
            name: tuf-keyserver-config
        - secretRef:
            name: tuf-keyserver-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: tuf-keyserver0
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.Boot
        resources:
          requests:
            cpu: '0.1'
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-keyserver
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-keyserver.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: tuf-keyserver
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-keyserver-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tufKeyserverDbPassword | b64enc }}
  TUF_VAULT_TOKEN: {{ .tufVaultToken | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-keyserver
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: tuf-keyserver0
  selector:
    app: tuf-keyserver
