---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-keyserver-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://mysql:3306/tuf_keyserver
  DB_USER: tuf_keyserver
  JAVA_OPTS: "-Xmx900m"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092
  KAFKA_HOST: kafka-0:9092
  KAFKA_TOPIC_SUFFIX: ce
  REPORT_METRICS: "false"
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-keyserver-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tufKeyserverDaemonDbPassword | b64enc }}
  TUF_VAULT_TOKEN: {{ .tufKeyserverVaultToken | b64enc }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuf-keyserver-daemon
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver-daemon
    spec:
      containers:
      - image: {{ .tufKeyserverImage }}
        name: tuf-keyserver-daemon
        envFrom:
        - configMapRef:
            name: tuf-keyserver-daemon-config
        - secretRef:
            name: tuf-keyserver-daemon-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: tuf-keyserver0
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.daemon.KeyGenerationDaemon
        resources:
          requests:
            cpu: '0.1'
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
      imagePullSecrets:
      - name: atsk8sregistrykey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tuf-keyserver-daemon
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tuf-keyserver-daemon.{{ .externalDomain }}
    http:
      paths:
      - backend:
          serviceName: tuf-keyserver-daemon
          servicePort: 80
